"use client";
import { useState } from "react";
import { Landmark, Wallet, Plus, Star, Pencil, Trash2, X, ArrowUpRight, ArrowDownLeft } from "lucide-react";
import type { Account } from "@/lib/store";
import { formatPHP, minorToInput } from "@/lib/money";

type Draft={name:string;type:"cash"|"bank";openingBalance:string};
export function AccountsView({initial}:{initial:Account[]}){
 const [accounts,setAccounts]=useState(initial);const [open,setOpen]=useState(false);const [editing,setEditing]=useState<Account|null>(null);const [draft,setDraft]=useState<Draft>({name:"",type:"cash",openingBalance:"0.00"});const [error,setError]=useState("");const [busy,setBusy]=useState(false);
 async function refresh(){const result=await fetch("/api/accounts").then(r=>r.json());if(result.accounts)setAccounts(result.accounts);}
 function create(){setEditing(null);setDraft({name:"",type:"cash",openingBalance:"0.00"});setError("");setOpen(true);}
 function edit(account:Account){setEditing(account);setDraft({name:account.name,type:account.type,openingBalance:minorToInput(account.openingMinor)});setError("");setOpen(true);}
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");try{const response=await fetch(editing?`/api/accounts/${editing.id}`:"/api/accounts",{method:editing?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(draft)});const result=await response.json();if(!response.ok)throw new Error(result.error??"Could not save account.");setOpen(false);await refresh();}catch(err){setError(err instanceof Error?err.message:"Could not save account.");}finally{setBusy(false);}}
 async function setDefault(account:Account){const response=await fetch(`/api/accounts/${account.id}/default`,{method:"POST"});const result=await response.json();if(!response.ok){setError(result.error);return;}await refresh();}
 async function remove(account:Account){if(!window.confirm(`Delete ${account.name}? Accounts with transaction history cannot be deleted.`))return;const response=await fetch(`/api/accounts/${account.id}`,{method:"DELETE"});const result=await response.json();if(!response.ok){setError(result.error);return;}await refresh();}
 return <div className="page-stack"><section className="page-heading-row"><div><div className="eyebrow">YOUR MONEY</div><h1>Accounts</h1><p className="subtitle">Cash and bank balances, kept separately from your sign-in.</p></div><button className="button button-primary" onClick={create}><Plus size={16}/> New account</button></section>
  <div className="notice-box">Opening balances set a starting point. They change your current balance, but are not income and do not create a transaction.</div>
  {error&&!open&&<p className="error-text" role="alert">{error}</p>}
  {accounts.length?<section className="account-grid">{accounts.map(account=><article className="account-card" key={account.id}><div className="account-card-top"><div><div className="account-type">{account.type==="cash"?<Wallet size={14} style={{display:"inline",marginRight:5}}/>:<Landmark size={14} style={{display:"inline",marginRight:5}}/>}{account.type} account</div><h2 className="account-name">{account.name}</h2></div>{account.isDefault&&<span className="badge badge-green">Default</span>}</div><div className="account-balance">{formatPHP(account.balanceMinor)}</div><div className="account-opening">Opening balance {formatPHP(account.openingMinor)}</div><div className="account-actions">{!account.isDefault&&<button className="button button-small button-secondary" onClick={()=>setDefault(account)}><Star size={13}/> Make default</button>}<button className="icon-button" aria-label={`Edit ${account.name}`} onClick={()=>edit(account)}><Pencil size={15}/></button><button className="icon-button" aria-label={`Delete ${account.name}`} onClick={()=>remove(account)}><Trash2 size={15}/></button></div></article>)}</section>:<article className="panel-empty"><div style={{display:"grid",justifyItems:"center",gap:8}}><Wallet size={24}/><strong>Create your first financial account</strong><span>Start with cash or a bank account; its opening balance can be zero.</span><button className="button button-primary" onClick={create}><Plus size={15}/> Add account</button></div></article>}
  <article className="panel"><div className="panel-heading"><div><h2>How account balances work</h2><p>Balances are calculated from your opening amount and owned transactions.</p></div></div><div className="activity-list"><div className="activity-row"><div className="activity-icon"><ArrowDownLeft size={17}/></div><div className="activity-copy"><strong>Income</strong><span>Added to the account you choose.</span></div></div><div className="activity-row"><div className="activity-icon expense"><ArrowUpRight size={17}/></div><div className="activity-copy"><strong>Expense</strong><span>Subtracted from the selected account.</span></div></div><div className="activity-row"><div className="activity-icon transfer"><ArrowUpRight size={17}/></div><div className="activity-copy"><strong>Transfer</strong><span>Moves money between your accounts without changing income or spending totals.</span></div></div></div></article>
  {open&&<div className="modal-backdrop" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)setOpen(false);}}><section className="modal-card" role="dialog" aria-modal="true" aria-labelledby="account-title"><div className="modal-heading"><div><h2 id="account-title">{editing?"Edit account":"New financial account"}</h2><p>Opening balance is not recorded as income.</p></div><button className="modal-close" aria-label="Close" onClick={()=>setOpen(false)}><X size={16}/></button></div><form onSubmit={save}><div className="form-grid"><label className="field-label span-2">Account name<input autoFocus required maxLength={80} value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})} placeholder="Everyday cash"/></label><label className="field-label">Type<select value={draft.type} onChange={e=>setDraft({...draft,type:e.target.value as Draft["type"]})}><option value="cash">Cash</option><option value="bank">Bank</option></select></label><label className="field-label">Opening balance<input inputMode="decimal" required value={draft.openingBalance} onChange={e=>setDraft({...draft,openingBalance:e.target.value})} placeholder="0.00"/></label></div>{error&&<p className="error-text" role="alert" style={{marginTop:12}}>{error}</p>}<div className="modal-footer"><button type="button" className="button" onClick={()=>setOpen(false)}>Cancel</button><button disabled={busy} className="button button-primary">{busy?"Saving…":editing?"Save changes":"Create account"}</button></div></form></section></div>}
 </div>;
}
