"use client";
import { useState } from "react";
import Link from "next/link";
import { Copy, KeyRound, Shield, UserCheck, UserRoundX } from "lucide-react";

type UserItem={id:string;username:string;role:"admin"|"user";enabled:boolean;createdAt:string};
export function AdminView({initial}:{initial:UserItem[]}){
 const [users,setUsers]=useState(initial);const [notice,setNotice]=useState("");const [error,setError]=useState("");const [reset,setReset]=useState<{username:string;token:string}|null>(null);const [busy,setBusy]=useState<string|null>(null);
 async function refresh(){const result=await fetch("/api/admin/users").then(r=>r.json());if(result.users)setUsers(result.users);}
 async function toggle(user:UserItem){setBusy(user.id);setError("");const response=await fetch("/api/admin/users",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({userId:user.id,enabled:!user.enabled})});const result=await response.json();if(!response.ok)setError(result.error??"Could not update user access.");else{setNotice(`${user.username} is ${user.enabled?"disabled":"enabled"}.`);await refresh();}setBusy(null);}
 async function issueReset(user:UserItem){setError("");setNotice("");const response=await fetch(`/api/admin/users/${user.id}/reset`,{method:"POST"});const result=await response.json();if(!response.ok){setError(result.error??"Could not issue reset credential.");return;}setReset({username:user.username,token:result.resetToken});}
 async function copyToken(){if(!reset)return;await navigator.clipboard.writeText(reset.token);setNotice("Reset credential copied. Share it securely with the user; it expires in 15 minutes and works once.");}
 return <div className="page-stack"><section className="page-heading-row"><div><div className="eyebrow">INSTANCE ACCESS</div><h1>Administration</h1><p className="subtitle">Manage account access without opening anyone’s personal ledger.</p></div><span className="stat-icon green"><Shield size={17}/></span></section>
 <div className="notice-box"><strong>Privacy boundary.</strong> Admin access does not include anyone’s accounts, balances, transactions, categories, goals, or assistant conversations.</div>{notice&&<div className="notice-box" role="status">{notice}</div>}{error&&<div className="notice-box danger" role="alert">{error}</div>}
 {reset&&<article className="panel"><div className="panel-heading"><div><h2>One-time reset for {reset.username}</h2><p>Give this credential to the user securely. It expires in 15 minutes and is shown only once.</p></div><KeyRound size={17} color="#7d8d80"/></div><div className="reset-token">{reset.token}</div><div className="account-actions"><button className="button button-small" onClick={copyToken}><Copy size={13}/> Copy credential</button><Link className="button button-small" href="/reset">Reset page <KeyRound size={13}/></Link><button className="button button-text button-small" onClick={()=>setReset(null)}>Dismiss</button></div></article>}
 <article className="panel"><div className="panel-heading"><div><h2>Users</h2><p>{users.length} registered {users.length===1?"user":"users"}</p></div></div><div>{users.map(user=><div className="admin-user-row" key={user.id}><div className="admin-user-name"><span className="avatar">{user.username.slice(0,1).toUpperCase()}</span><div><strong>{user.username}</strong><span>{user.role==="admin"?"Administrator":"Regular user"}</span></div></div><span className="admin-status"><span className={`badge ${user.enabled?"badge-green":"badge-coral"}`}>{user.enabled?"Enabled":"Disabled"}</span></span><span className="table-muted">Joined {new Date(user.createdAt).toLocaleDateString("en-PH")}</span><div className="admin-actions" style={{display:"flex",justifyContent:"flex-end",gap:7}}>{user.enabled&&user.role!=="admin"&&<button className="button button-small" onClick={()=>issueReset(user)}><KeyRound size={13}/> Issue reset</button>}{user.role!=="admin"&&<button className={`button button-small ${user.enabled?"button-danger":"button-secondary"}`} disabled={busy===user.id} onClick={()=>toggle(user)}>{user.enabled?<UserRoundX size={13}/>:<UserCheck size={13}/>} {user.enabled?"Disable":"Re-enable"}</button>}</div></div>)}</div>{!users.length&&<div className="panel-empty">No registered users.</div>}</article>
 <p className="page-note">Disabling an account blocks new sign-ins and requests. It does not delete that user’s data. Reset credentials do not reveal or set a user’s new password.</p>
 </div>;
}
