"use client";
import { FormEvent, KeyboardEvent, useEffect, useRef, useState } from "react";
import Link from "next/link";
import { Bot, Plus, Send, Trash2, Undo2, LockKeyhole, Sparkles } from "lucide-react";
import { formatPHP } from "@/lib/money";
import { isUndoAvailable } from "@/lib/dates";

type ChatMessage={id:string;role:"user"|"assistant";content:string;createdAt:string;transaction?:{id:string;kind:string;amountMinor:number;description:string;date:string;categoryName:string|null;accountName:string;undoUntil:string|null}|null};
export type Conversation={id:string;title:string;createdAt:string;updatedAt:string};
export type ChatData={id:string;title:string;messages:ChatMessage[]};
let transientMessageSequence=0;
function nextTransientMessageId(){return `message-${Date.now()}-${++transientMessageSequence}`;}
export function AssistantView({initialConversations,initialChat,enabled,configured}:{initialConversations:Conversation[];initialChat:ChatData|null;enabled:boolean;configured:boolean}){
 const [conversations,setConversations]=useState(initialConversations);const [activeId,setActiveId]=useState<string|null>(initialChat?.id??null);const [messages,setMessages]=useState<ChatMessage[]>(initialChat?.messages??[]);const [prompt,setPrompt]=useState("");const [busy,setBusy]=useState(false);const [notice,setNotice]=useState("");const [tick,setTick]=useState(0);const bottom=useRef<HTMLDivElement>(null);
 useEffect(()=>{const update=()=>setTick(Date.now());update();const id=window.setInterval(update,1000);return()=>window.clearInterval(id);},[]);
 useEffect(()=>{bottom.current?.scrollIntoView({behavior:"smooth",block:"end"});},[messages,busy]);
 async function refreshList(){const result=await fetch("/api/conversations").then(r=>r.json());if(result.conversations)setConversations(result.conversations);}
 async function openConversation(id:string){setNotice("");const result=await fetch(`/api/conversations?id=${encodeURIComponent(id)}`).then(r=>r.json());if(result.conversation){setActiveId(id);setMessages(result.conversation.messages??[]);}}
 function newConversation(){setActiveId(null);setMessages([]);setNotice("");setPrompt("");}
 async function send(event?:FormEvent){event?.preventDefault();const text=prompt.trim();if(!text||busy||!enabled)return;setPrompt("");setNotice("");const localId=nextTransientMessageId();setMessages(previous=>[...previous,{id:localId,role:"user",content:text,createdAt:new Date().toISOString()}]);setBusy(true);
  try{let conversationId=activeId;if(!conversationId){const created=await fetch("/api/conversations",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({title:text.slice(0,80)})}).then(r=>r.json());if(!created.id)throw new Error(created.error??"Could not create conversation.");conversationId=created.id;setActiveId(conversationId);}
   const response=await fetch("/api/assistant",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({prompt:text,conversationId})});const result=await response.json();if(!response.ok)throw new Error(result.error??"Assistant could not answer.");
   setMessages(previous=>[...previous,{id:nextTransientMessageId(),role:"assistant",content:result.answer,createdAt:new Date().toISOString(),transaction:result.transaction?{id:result.transaction.id,kind:result.transaction.kind,amountMinor:result.transaction.amountMinor,description:result.transaction.description,date:result.transaction.date,categoryName:result.transaction.categoryName,accountName:result.transaction.accountName,undoUntil:result.undoUntil}:null}]);await refreshList();
  }catch(error){setNotice(error instanceof Error?error.message:"Assistant could not answer.");}finally{setBusy(false);}}
 async function undo(id:string){const response=await fetch(`/api/transactions/${id}?undo=1`,{method:"DELETE"});const result=await response.json();if(!response.ok){setNotice(result.error??"Undo is no longer available.");return;}setMessages(previous=>previous.map(message=>message.transaction?.id===id?{...message,transaction:null}:message));setNotice("Transaction undone.");}
 async function deleteConversation(id:string){if(!window.confirm("Delete this conversation? Finance records will not be changed."))return;const response=await fetch(`/api/conversations/${id}`,{method:"DELETE"});const result=await response.json();if(!response.ok){setNotice(result.error??"Could not delete conversation.");return;}setConversations(previous=>previous.filter(item=>item.id!==id));if(activeId===id)newConversation();}
 function onKeyDown(event:KeyboardEvent<HTMLTextAreaElement>){if(event.key==="Enter"&&!event.shiftKey){event.preventDefault();void send();}}
 const activeTitle=conversations.find(item=>item.id===activeId)?.title??initialChat?.title??"New conversation";
 return <div className="page-stack"><section className="page-heading-row"><div><div className="eyebrow">OPTIONAL · PRIVATE TO YOU</div><h1>Assistant</h1><p className="subtitle">Capture a transaction or ask about your recorded actuals.</p></div><Link className="button" href="/settings"><LockKeyhole size={15}/> Privacy settings</Link></section>
 {!enabled&&<div className="notice-box warning"><strong>{configured?"The assistant is off until you opt in.":"The assistant is not configured."}</strong> {configured?"Review the provider route and retention disclosure in Settings, then opt in if you agree.":"The instance operator must configure the Codex-LB endpoint and an accurate retention/logging disclosure."} <Link className="quiet-link" href="/settings">Open Settings →</Link></div>}
 {notice&&<div className="notice-box" role="status">{notice}</div>}
 <section className="chat-layout"><aside className="panel chat-sidebar"><button className="button button-primary full-width" onClick={newConversation}><Plus size={15}/> New conversation</button><div className="chat-list">{conversations.map(item=><div className={`chat-item ${activeId===item.id?"active":""}`} key={item.id} style={{display:"flex",alignItems:"center",flexDirection:"row",justifyContent:"space-between"}}><button onClick={()=>openConversation(item.id)} style={{background:"none",border:0,padding:0,textAlign:"left",minWidth:0,flex:1,cursor:"pointer",color:"inherit"}}><strong>{item.title||"Conversation"}</strong><span>{new Date(item.updatedAt).toLocaleDateString("en-PH")}</span></button><button className="icon-button" aria-label={`Delete conversation ${item.title}`} onClick={()=>deleteConversation(item.id)}><Trash2 size={13}/></button></div>)}{!conversations.length&&<div className="page-note" style={{padding:10}}>Your conversations will appear here.</div>}</div></aside>
 <article className="panel chat-panel"><header className="chat-head"><span className="chat-mark"><Sparkles size={18}/></span><div style={{flex:1,minWidth:0}}><strong>{activeTitle}</strong><span>{enabled?"Uses your private ledger context only":"Assistant disabled"}</span></div><button className="button button-small" onClick={newConversation}><Plus size={13}/> New</button></header>
 <div className="chat-messages" aria-live="polite">{messages.length?messages.map(message=><div className={`chat-bubble ${message.role}`} key={message.id}>{message.content}{message.transaction&&<div className="chat-transaction"><strong>{formatPHP(message.transaction.amountMinor)} · {message.transaction.description||message.transaction.categoryName||message.transaction.kind}</strong><span>{message.transaction.categoryName??message.transaction.kind} · {message.transaction.accountName} · {message.transaction.date}</span>{message.transaction.undoUntil&&isUndoAvailable(message.transaction.undoUntil,tick)&&<button className="undo-link" onClick={()=>undo(message.transaction!.id)}><Undo2 size={12} style={{verticalAlign:"-2px"}}/> Undo · {Math.max(1,Math.ceil((Date.parse(message.transaction.undoUntil)-tick)/1000))}s</button>}</div>}</div>):<div className="chat-empty"><span className="chat-mark"><Bot size={20}/></span><strong>What would you like to do?</strong><p>Try “Jollibee lunch 250” to log a purchase, or ask how much you spent this month.</p></div>}{busy&&<div className="chat-bubble assistant">Checking your request…</div>}<div ref={bottom}/></div>
 <form className="chat-composer" onSubmit={send}><label className="sr-only" htmlFor="assistant-prompt">Message Tally assistant</label><textarea id="assistant-prompt" rows={1} value={prompt} disabled={!enabled||busy} onChange={e=>setPrompt(e.target.value)} onKeyDown={onKeyDown} placeholder={enabled?"Ask a question or describe a transaction…":"Enable the assistant in Settings to continue."}/><button className="button button-primary" disabled={!enabled||busy||!prompt.trim()} aria-label="Send message"><Send size={16}/></button></form></article></section>
 </div>;
}
