"use client";
import { useState } from "react";
import { CalendarDays, Check, CirclePlus, Pencil, Plus, Target, Trash2, UserMinus, Users, X } from "lucide-react";
import { formatPHP, minorToInput } from "@/lib/money";
import { todayInManila } from "@/lib/dates";

export type GoalMemberView={userId:string|null;username:string;status:string};
export type ContributionView={id:string;userId:string|null;memberName:string;amountMinor:number;note:string;date:string};
export type GoalView={id:string;name:string;targetMinor:number;deadline:string|null;status:string;managerId:string|null;raisedMinor:number;members:GoalMemberView[];contributions:ContributionView[]};
export type InvitationView={id:string;goalId:string;goalName:string;managerName:string;invitedAt:string};
type GoalDraft={name:string;target:string;deadline:string};
export function GoalsView({initialGoals,initialInvitations,userId}:{initialGoals:GoalView[];initialInvitations:InvitationView[];userId:string}){
 const [goals,setGoals]=useState(initialGoals);const [invitations,setInvitations]=useState(initialInvitations);const [modal,setModal]=useState<"create"|"edit"|null>(null);const [editing,setEditing]=useState<GoalView|null>(null);const [draft,setDraft]=useState<GoalDraft>({name:"",target:"",deadline:""});const [error,setError]=useState("");const [busy,setBusy]=useState(false);const [inviteName,setInviteName]=useState<Record<string,string>>({});const [contrib,setContrib]=useState<Record<string,{amount:string;note:string}>>({});const [notice,setNotice]=useState("");
 async function refresh(){const r=await fetch("/api/goals").then(x=>x.json());if(r.goals)setGoals(r.goals);if(r.invitations)setInvitations(r.invitations);}
 function create(){setEditing(null);setDraft({name:"",target:"",deadline:""});setError("");setModal("create");}
 function edit(goal:GoalView){setEditing(goal);setDraft({name:goal.name,target:minorToInput(goal.targetMinor),deadline:goal.deadline??""});setError("");setModal("edit");}
 async function saveGoal(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");try{const response=await fetch(editing?`/api/goals/${editing.id}`:"/api/goals",{method:editing?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:draft.name,target:draft.target,deadline:draft.deadline||null})});const result=await response.json();if(!response.ok)throw new Error(result.error??"Could not save goal.");setModal(null);await refresh();}catch(err){setError(err instanceof Error?err.message:"Could not save goal.");}finally{setBusy(false);}}
 async function answerInvite(id:string,accept:boolean){const response=await fetch("/api/invitations",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({membershipId:id,accept})});const result=await response.json();if(!response.ok){setNotice(result.error);return;}await refresh();}
 async function invite(goal:GoalView){const username=inviteName[goal.id]?.trim();if(!username)return;const response=await fetch(`/api/goals/${goal.id}/members`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({username})});const result=await response.json();if(!response.ok){setNotice(result.error??"Could not invite user.");return;}setInviteName({...inviteName,[goal.id]:""});setNotice(`Invitation sent to ${username}.`);await refresh();}
 async function leave(goal:GoalView){if(!window.confirm("Leave this shared goal? Its history will remain for the other members."))return;const response=await fetch(`/api/goals/${goal.id}/members`,{method:"DELETE"});const result=await response.json();if(!response.ok){setNotice(result.error);return;}await refresh();}
 async function removeMember(goal:GoalView,userId:string|null,name:string){if(!userId||!window.confirm(`Remove ${name} from this goal? Their contribution history stays visible.`))return;const response=await fetch(`/api/goals/${goal.id}/members?userId=${encodeURIComponent(userId)}`,{method:"DELETE"});const result=await response.json();if(!response.ok){setNotice(result.error);return;}await refresh();}
 async function addContribution(goal:GoalView,e:React.FormEvent){e.preventDefault();const draftContribution=contrib[goal.id]??{amount:"",note:""};const response=await fetch(`/api/goals/${goal.id}/contributions`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...draftContribution,date:todayInManila()})});const result=await response.json();if(!response.ok){setNotice(result.error??"Could not add contribution.");return;}setNotice("Contribution added to goal history.");setContrib({...contrib,[goal.id]:{amount:"",note:""}});await refresh();}
 async function editContribution(item:ContributionView){const amount=window.prompt("Update this contribution amount (PHP)",minorToInput(item.amountMinor));if(amount===null)return;const note=window.prompt("Update its note",item.note);if(note===null)return;const response=await fetch(`/api/contributions/${item.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({amount,note})});const result=await response.json();if(!response.ok){setNotice(result.error??"Could not update contribution.");return;}await refresh();}
 async function deleteContribution(item:ContributionView){if(!window.confirm("Delete your contribution?"))return;const response=await fetch(`/api/contributions/${item.id}`,{method:"DELETE"});const result=await response.json();if(!response.ok){setNotice(result.error);return;}await refresh();}
 return <div className="page-stack"><section className="page-heading-row"><div><div className="eyebrow">SAVE TOGETHER</div><h1>Shared goals</h1><p className="subtitle">Shared progress, separate personal finances.</p></div><button className="button button-primary" onClick={create}><Plus size={16}/> Create a goal</button></section>
 {notice&&<div className="notice-box" role="status">{notice}</div>}
 {invitations.length>0&&<section className="panel"><div className="panel-heading"><div><h2>Invitations</h2><p>Accept before you can see the goal or its contribution history.</p></div><Users size={17} color="#7c9d85"/></div><div className="activity-list">{invitations.map(invite=><div key={invite.id} className="activity-row"><div className="activity-icon"><Users size={16}/></div><div className="activity-copy"><strong>{invite.goalName}</strong><span>Invited by {invite.managerName}</span></div><div style={{display:"flex",gap:7}}><button className="button button-primary button-small" onClick={()=>answerInvite(invite.id,true)}><Check size={13}/> Accept</button><button className="button button-small" onClick={()=>answerInvite(invite.id,false)}>Decline</button></div></div>)}</div></section>}
 {goals.length?<section className="goal-grid">{goals.map(goal=>{const manager=goal.managerId===userId;const completed=goal.status==="completed";const percent=Math.min(100,goal.raisedMinor/goal.targetMinor*100);return <article className="goal-card" key={goal.id}><div className="goal-card-top"><div><div className="account-type">{completed?"GOAL COMPLETE":"SHARED GOAL"}</div><h2 style={{margin:"5px 0 0",fontSize:15}}>{goal.name}</h2></div>{manager&&<button className="icon-button" aria-label={`Edit ${goal.name}`} onClick={()=>edit(goal)}><Pencil size={15}/></button>}</div><div><div className="goal-card-meta"><span>{goal.deadline?<><CalendarDays size={12} style={{verticalAlign:"-2px",marginRight:4}}/>{goal.deadline}</>:"No deadline"}</span><span>{goal.members.filter(m=>m.status==="accepted").length} members</span></div><div className="goal-progress" style={{marginTop:10}}>{formatPHP(goal.raisedMinor)} <span className="page-note">of {formatPHP(goal.targetMinor)}</span></div><div className="bar-track" style={{marginTop:9,height:8}}><span className="bar-fill bar-goal" style={{width:`${percent}%`}}/></div></div><div className="goal-member-row">{goal.members.map((member,i)=><span className="member-chip" key={`${member.userId??member.username}-${i}`}>{member.username}{member.userId===goal.managerId?" · manager":member.status==="invited"?" · invited":""}</span>)}</div>
 <div><div className="page-note" style={{marginBottom:6}}>Contribution history</div>{goal.contributions.length?<div className="contribution-list">{goal.contributions.slice(0,5).map(item=><div className="contribution-row" key={item.id}><span><strong>{item.memberName}</strong><span className="table-muted"> · {item.date}{item.note?` · ${item.note}`:""}</span></span><span>{formatPHP(item.amountMinor)}{item.userId===userId&&<><button className="icon-button" aria-label="Edit your contribution" onClick={()=>editContribution(item)}><Pencil size={12}/></button><button className="icon-button" aria-label="Delete your contribution" onClick={()=>deleteContribution(item)}><Trash2 size={12}/></button></>}</span></div>)}</div>:<div className="table-muted">No contributions yet.</div>}</div>
 {!completed&&<form className="goal-contribute-form" onSubmit={e=>addContribution(goal,e)}><div style={{display:"flex",gap:7}}><label className="field-label" style={{flex:1}}>Your contribution<input required inputMode="decimal" placeholder="PHP amount" value={contrib[goal.id]?.amount??""} onChange={e=>setContrib({...contrib,[goal.id]:{...contrib[goal.id],amount:e.target.value,note:contrib[goal.id]?.note??""}})}/></label><label className="field-label" style={{flex:1}}>Note<input maxLength={200} placeholder="Optional" value={contrib[goal.id]?.note??""} onChange={e=>setContrib({...contrib,[goal.id]:{...contrib[goal.id],note:e.target.value,amount:contrib[goal.id]?.amount??""}})}/></label></div><button className="button button-secondary button-small"><CirclePlus size={14}/> Add contribution</button></form>}{completed&&!manager&&<div className="notice-box">The target is met. The manager can raise it to continue.</div>}
 {manager&&<div className="invite-form"><label className="field-label">Invite a registered user<input maxLength={32} value={inviteName[goal.id]??""} onChange={e=>setInviteName({...inviteName,[goal.id]:e.target.value})} placeholder="Username"/></label><button className="button button-small" onClick={()=>invite(goal)}><Plus size={13}/> Invite</button></div>}
 <div className="goal-actions">{goal.members.filter(m=>m.status==="accepted"&&m.userId!==userId).map(member=><button key={member.userId??member.username} className="button button-text button-small" onClick={()=>removeMember(goal,member.userId,member.username)}><UserMinus size={13}/> Remove {member.username}</button>)}<button className="button button-text button-small" onClick={()=>leave(goal)}><X size={13}/> Leave goal</button></div>
 </article>})}</section>:!invitations.length&&<article className="panel"><div className="panel-empty"><Target size={24} style={{marginBottom:9,color:"#74a181"}}/><strong>No shared goals yet</strong>Create a savings goal, then invite a registered user to join.</div></article>}
 {modal&&<div className="modal-backdrop" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)setModal(null);}}><section className="modal-card" role="dialog" aria-modal="true" aria-labelledby="goal-modal-title"><div className="modal-heading"><div><h2 id="goal-modal-title">{editing?"Edit shared goal":"Create a shared goal"}</h2><p>Contributions stay separate from personal account balances.</p></div><button className="modal-close" aria-label="Close" onClick={()=>setModal(null)}><X size={16}/></button></div><form onSubmit={saveGoal}><div className="form-grid"><label className="field-label span-2">Goal name<input required autoFocus maxLength={100} value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})} placeholder="Summer in Palawan"/></label><label className="field-label">Target in PHP<input required inputMode="decimal" value={draft.target} onChange={e=>setDraft({...draft,target:e.target.value})} placeholder="25,000.00"/></label><label className="field-label">Deadline (optional)<input type="date" value={draft.deadline} onChange={e=>setDraft({...draft,deadline:e.target.value})}/></label></div>{error&&<p className="error-text" role="alert" style={{marginTop:12}}>{error}</p>}<div className="modal-footer"><button type="button" className="button" onClick={()=>setModal(null)}>Cancel</button><button className="button button-primary" disabled={busy}>{busy?"Saving…":editing?"Save changes":"Create goal"}</button></div></form></section></div>}
 </div>;
}
