"use client";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { AlertTriangle, Bot, KeyRound, ShieldCheck, Trash2, X } from "lucide-react";
import type { PublicUser } from "@/lib/store";
import { ASSISTANT_SETTINGS_UPDATED_EVENT } from "@/lib/client-events";

type Provider={configured:boolean;baseUrl:string|null;model:string|null;disclosure:string|null};type AdminUser={id:string;username:string;role:string;enabled:boolean;createdAt:string};
export function SettingsView({user}:{user:Pick<PublicUser,"id"|"role">}){
 const router=useRouter();const [provider,setProvider]=useState<Provider|null>(null);const [optIn,setOptIn]=useState(false);const [hash,setHash]=useState("");const [confirmed,setConfirmed]=useState(false);const [loading,setLoading]=useState(true);const [notice,setNotice]=useState("");const [error,setError]=useState("");const [adminUsers,setAdminUsers]=useState<AdminUser[]>([]);
 const [deleteOpen,setDeleteOpen]=useState(false);const [password,setPassword]=useState("");const [handoff,setHandoff]=useState("");const [deleteChecked,setDeleteChecked]=useState(false);const [deleting,setDeleting]=useState(false);
 useEffect(()=>{
  const controller=new AbortController();
  void fetch("/api/settings",{signal:controller.signal}).then(async response=>{
   const data=await response.json();
   if(response.ok){setProvider(data.provider);setOptIn(data.assistantOptIn);setHash(data.disclosureHash??"");}
   if(user.role==="admin"){
    const result=await fetch("/api/admin/users",{signal:controller.signal}).then(r=>r.json());
    if(result.users)setAdminUsers(result.users);
   }
  }).catch(()=>{if(!controller.signal.aborted)setError("Could not load settings.");}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});
  return()=>controller.abort();
 },[user.role]);
 async function toggleAssistant(){setError("");setNotice("");if(!optIn&&!confirmed){setError("Read the full provider disclosure and check the consent box before enabling.");return;}const response=await fetch("/api/settings",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({assistantOptIn:!optIn,confirmedDisclosureHash:!optIn?hash:undefined})});const result=await response.json();if(!response.ok){setError(result.error??"Could not update assistant setting.");return;}setOptIn(result.assistantOptIn);setConfirmed(false);setNotice(result.assistantOptIn?"Assistant enabled for this provider disclosure.":"Assistant disabled.");window.dispatchEvent(new Event(ASSISTANT_SETTINGS_UPDATED_EVENT));}
 async function deleteAccount(){setError("");setDeleting(true);try{const response=await fetch("/api/account",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({password,...(handoff?{adminHandoffTo:handoff}:{})})});const result=await response.json();if(!response.ok)throw new Error(result.error??"Could not delete account.");router.replace("/register");router.refresh();}catch(err){setError(err instanceof Error?err.message:"Could not delete account.");}finally{setDeleting(false);}}
 const enabledOthers=adminUsers.filter(item=>item.id!==user.id&&item.enabled);
 return <div className="page-stack"><section className="page-heading-row"><div><div className="eyebrow">YOUR PREFERENCES</div><h1>Settings</h1><p className="subtitle">Control assistant access and your Tally account.</p></div></section>
 {notice&&<div className="notice-box" role="status">{notice}</div>}{error&&!deleteOpen&&<div className="notice-box danger" role="alert">{error}</div>}
 <section className="settings-grid"><article className="panel"><div className="panel-heading"><div><h2>Optional assistant</h2><p>Hosted processing is off unless you opt in.</p></div><span className="stat-icon green"><Bot size={17}/></span></div>
 {loading?<div className="panel-empty">Loading provider settings…</div>:provider?.configured?<><div className="setting-row"><div><strong>Assistant access</strong><span>{optIn?"Enabled for the current provider disclosure":"Disabled"}</span></div><button className="switch" role="switch" aria-checked={optIn} aria-label="Enable hosted assistant" onClick={toggleAssistant}/></div><div className="notice-box" style={{marginTop:15}}><strong>Configured provider path</strong><div style={{marginTop:5,wordBreak:"break-word"}}>{provider.baseUrl}</div><div style={{marginTop:4}}>Model: {provider.model}</div></div><div className="notice-box warning disclosure" style={{marginTop:13}}><strong>Provider and retention disclosure</strong>{"\n"}{provider.disclosure}</div>{!optIn&&<label className="toggle-label" style={{marginTop:14}}><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I have read this disclosure and agree to send my prompts and only the minimum relevant finance data to the configured hosted provider when I use the assistant.</label>}<p className="page-note" style={{marginTop:12}}>Provider credentials remain on the server. Tally calculates finance answers and scopes transaction actions to your ledger. If the endpoint, model, or disclosure changes, consent is required again.</p></>:<div className="notice-box warning"><strong>Not configured by the operator.</strong><p style={{margin:"6px 0 0"}}>The assistant remains unavailable until the server has a Codex-LB base URL, model, API key, and an accurate disclosure of the configured upstream path and its retention/logging behavior. No finance data is sent while disabled.</p></div>}
 </article><article className="panel"><div className="panel-heading"><div><h2>Privacy boundaries</h2><p>What other people can and cannot see.</p></div><ShieldCheck size={18} color="#6c9b7a"/></div><div className="activity-list"><div className="activity-row"><div className="activity-icon"><ShieldCheck size={16}/></div><div className="activity-copy"><strong>Personal ledger</strong><span>Only you can access your accounts, transactions, and categories. Admin status does not grant access.</span></div></div><div className="activity-row"><div className="activity-icon transfer"><Bot size={16}/></div><div className="activity-copy"><strong>Assistant messages</strong><span>Private to your account. The floating assistant does not show a past-chat list; stored messages are removed when you delete your account.</span></div></div><div className="activity-row"><div className="activity-icon expense"><AlertTriangle size={16}/></div><div className="activity-copy"><strong>Home-server operator</strong><span>The host operator can access the SQLite database and local backups.</span></div></div></div></article></section>
 <article className="panel"><div className="panel-heading"><div><h2>Account access</h2><p>{user.role==="admin"?"You are the instance admin. Hand off admin access before deleting if other users are enabled.":"You can permanently remove your account and private data."}</p></div><KeyRound size={17} color="#88938c"/></div><button className="button button-danger" onClick={()=>{setDeleteOpen(true);setError("");}}><Trash2 size={15}/> Delete my account</button></article>
 {deleteOpen&&<div className="modal-backdrop" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)setDeleteOpen(false);}}><section className="modal-card" role="dialog" aria-modal="true" aria-labelledby="delete-account-title"><div className="modal-heading"><div><h2 id="delete-account-title">Delete your Tally account?</h2><p>This permanently removes your private data.</p></div><button className="modal-close" aria-label="Close" onClick={()=>setDeleteOpen(false)}><X size={16}/></button></div><div className="notice-box danger">Your financial accounts, transactions, categories, and assistant conversations will be deleted and cannot be recovered in the app. Shared-goal contributions remain under “Former member”; goals pass to the first active accepted invitee or are archived if there is none.</div>{user.role==="admin"&&enabledOthers.length>0&&<label className="field-label" style={{marginTop:14}}>Hand admin access to<select required value={handoff} onChange={e=>setHandoff(e.target.value)}><option value="">Choose an enabled user</option>{enabledOthers.map(other=><option key={other.id} value={other.id}>{other.username}</option>)}</select></label>}<label className="field-label" style={{marginTop:14}}>Confirm with your password<input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} required/></label><label className="toggle-label" style={{marginTop:13}}><input type="checkbox" checked={deleteChecked} onChange={e=>setDeleteChecked(e.target.checked)}/>I understand this action is permanent and may hand admin access to the selected user.</label>{error&&<p className="error-text" role="alert" style={{marginTop:12}}>{error}</p>}<div className="modal-footer"><button className="button" onClick={()=>setDeleteOpen(false)}>Cancel</button><button className="button button-danger" disabled={deleting||!deleteChecked||(user.role==="admin"&&enabledOthers.length>0&&!handoff)} onClick={deleteAccount}>{deleting?"Deleting…":"Delete account permanently"}</button></div></section></div>}
 </div>;
}
