"use client";
import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { Plus, Pencil, Trash2, X, Search, FolderPlus } from "lucide-react";
import type { Account, Category, Transaction } from "@/lib/store";
import { formatPHP, minorToInput } from "@/lib/money";
import { isUndoAvailable, todayInManila } from "@/lib/dates";

type Draft = { amount: string; description: string; accountId: string; categoryId: string; date: string };
const blank = (accounts: Account[]): Draft => ({amount:"",description:"",accountId:accounts.find(a=>a.isDefault)?.id??accounts[0]?.id??"",categoryId:"",date:todayInManila()});
export function TransactionsView({initial,initialAccounts,initialCategories}:{initial:Transaction[];initialAccounts:Account[];initialCategories:Category[]}){
  const [transactions,setTransactions]=useState(initial);const [accounts,setAccounts]=useState(initialAccounts);const [categories,setCategories]=useState(initialCategories);
  const [search,setSearch]=useState("");const [open,setOpen]=useState(false);const [editing,setEditing]=useState<Transaction|null>(null);const [draft,setDraft]=useState<Draft>(blank(initialAccounts));const [error,setError]=useState("");const [busy,setBusy]=useState(false);
  const [categoryName,setCategoryName]=useState("");const [categoryType,setCategoryType]=useState<"income"|"expense">("expense");const [categoryNotice,setCategoryNotice]=useState("");
  const [now,setNow]=useState(0);
  useEffect(()=>{const update=()=>setNow(Date.now());update();const id=window.setInterval(update,1000);return()=>window.clearInterval(id);},[]);
  async function refresh(){const [t,a,c]=await Promise.all([fetch("/api/transactions").then(r=>r.json()),fetch("/api/accounts").then(r=>r.json()),fetch("/api/categories").then(r=>r.json())]);if(t.transactions)setTransactions(t.transactions);if(a.accounts)setAccounts(a.accounts);if(c.categories)setCategories(c.categories);}
  function startNew(){setEditing(null);setDraft(blank(accounts));setError("");setOpen(true);}
  function startEdit(tx:Transaction){if(tx.kind==="transfer"){window.location.assign("/accounts");return;}setEditing(tx);setDraft({amount:minorToInput(tx.amountMinor),description:tx.description,accountId:tx.accountId,categoryId:tx.categoryId??"",date:tx.date});setError("");setOpen(true);}
  async function save(e:React.FormEvent){e.preventDefault();const category=categories.find(item=>item.id===draft.categoryId);if(!category){setError("Choose a category.");return;}setBusy(true);setError("");try{const payload={kind:category.type,amount:draft.amount,description:draft.description,accountId:draft.accountId,categoryId:category.id,date:draft.date};const response=await fetch(editing?`/api/transactions/${editing.id}`:"/api/transactions",{method:editing?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const result=await response.json();if(!response.ok)throw new Error(result.error??"Could not save transaction.");setOpen(false);await refresh();}catch(err){setError(err instanceof Error?err.message:"Could not save transaction.");}finally{setBusy(false);}}
  async function remove(tx:Transaction,undo=false){if(!undo&&!window.confirm(`Permanently delete “${tx.description||tx.categoryName||tx.kind}”? This cannot be recovered in Tally.`))return;const response=await fetch(`/api/transactions/${tx.id}${undo?"?undo=1":""}`,{method:"DELETE"});const result=await response.json();if(!response.ok){setError(result.error??"Could not delete.");return;}await refresh();}
  async function addCategory(e:React.FormEvent){e.preventDefault();setCategoryNotice("");try{const response=await fetch("/api/categories",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:categoryName,type:categoryType})});const result=await response.json();if(!response.ok)throw new Error(result.error);setCategoryName("");setCategoryNotice("Category added.");await refresh();}catch(err){setCategoryNotice(err instanceof Error?err.message:"Could not add category.");}}
  async function renameCategory(category:Category){const name=window.prompt(`Rename ${category.name}`,category.name);if(!name||name===category.name)return;const response=await fetch(`/api/categories/${category.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({name})});const result=await response.json();if(!response.ok){setCategoryNotice(result.error??"Could not rename category.");return;}await refresh();}
  const shown=useMemo(()=>transactions.filter(tx=>`${tx.description} ${tx.categoryName??""} ${tx.accountName}`.toLowerCase().includes(search.toLowerCase())),[transactions,search]);
  return <div className="page-stack"><section className="page-heading-row"><div><div className="eyebrow">YOUR MONEY</div><h1>Transactions</h1><p className="subtitle">Every entry, in one private ledger.</p></div><button className="button button-primary" onClick={startNew}><Plus size={16}/> Add transaction</button></section>
    <article className="panel"><div className="content-toolbar"><div><h2 style={{margin:"0 0 4px",fontSize:14}}>Ledger activity</h2><span className="page-note">Income and expenses affect totals; transfers only move money.</span></div><label style={{position:"relative",display:"flex",alignItems:"center"}}><Search size={15} style={{position:"absolute",left:11,color:"#9aa49e"}}/><input className="search-input" style={{paddingLeft:34}} value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search this ledger"/></label></div>
      {error&&!open&&<p className="error-text" role="alert" style={{marginTop:12}}>{error}</p>}
      <div className="table-wrap" style={{marginTop:16}}><table className="list-table"><thead><tr><th>Transaction</th><th>Date</th><th>Type</th><th>Account</th><th className="table-number">Amount</th><th><span className="sr-only">Actions</span></th></tr></thead><tbody>{shown.map(tx=><tr key={tx.id}><td><div className="table-title">{tx.description||tx.categoryName||(tx.kind==="transfer"?"Transfer":tx.kind)}</div><div className="table-muted">{tx.kind==="transfer"?`To ${tx.destinationAccountName}`:`${tx.categoryName??""} · ${tx.kind}`}</div></td><td>{tx.date}</td><td><span className={`badge ${tx.kind==="income"?"badge-green":tx.kind==="expense"?"badge-coral":"badge-violet"}`}>{tx.kind}</span></td><td>{tx.accountName}</td><td className="table-number">{tx.kind==="expense"?"−":tx.kind==="income"?"+":""}{formatPHP(tx.amountMinor)}</td><td><div className="table-actions">{tx.kind==="transfer"?<Link className="button button-small" href="/accounts" aria-label="Manage transfer in Accounts">Manage</Link>:<>{tx.source==="assistant"&&isUndoAvailable(tx.undoUntil,now)&&<button className="button button-text button-small" onClick={()=>remove(tx,true)}>Undo</button>}<button className="icon-button" aria-label={`Edit ${tx.description||tx.categoryName||"transaction"}`} onClick={()=>startEdit(tx)}><Pencil size={15}/></button><button className="icon-button" aria-label={`Permanently delete ${tx.description||tx.categoryName||"transaction"}`} onClick={()=>remove(tx)}><Trash2 size={15}/></button></>}</div></td></tr>)}</tbody></table>{!shown.length&&<div className="panel-empty"><strong>{transactions.length?"No matching transactions":"Your ledger is ready"}</strong>{transactions.length?"Try a different search.":"Add your first income or expense."}</div>}</div>
    </article>
    <details className="panel category-settings"><summary style={{cursor:"pointer",fontSize:13,fontWeight:650,display:"flex",alignItems:"center",gap:8}}><FolderPlus size={16}/> Manage categories</summary><div style={{marginTop:16,display:"grid",gap:15}}><div className="goal-member-row">{categories.map(category=><button className="member-chip" key={category.id} onClick={()=>renameCategory(category)}>{category.name} · {category.type} <Pencil size={10}/></button>)}</div><form onSubmit={addCategory} style={{display:"flex",gap:8,flexWrap:"wrap"}}><input className="search-input" style={{maxWidth:220}} required maxLength={40} value={categoryName} onChange={e=>setCategoryName(e.target.value)} placeholder="New category"/><select className="search-input" style={{width:140}} value={categoryType} onChange={e=>setCategoryType(e.target.value as "income"|"expense")}><option value="expense">Expense</option><option value="income">Income</option></select><button className="button button-small" type="submit"><Plus size={14}/> Add</button></form>{categoryNotice&&<p className="form-notice" role="status">{categoryNotice}</p>}</div></details>
    {open&&<div className="modal-backdrop" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)setOpen(false);}}><section className="modal-card" role="dialog" aria-modal="true" aria-labelledby="transaction-title"><div className="modal-heading"><div><h2 id="transaction-title">{editing?"Edit transaction":"Add transaction"}</h2><p>Saved to your private ledger.</p></div><button className="modal-close" onClick={()=>setOpen(false)} aria-label="Close"><X size={16}/></button></div><form onSubmit={save}><div className="form-grid"><label className="field-label">Amount in PHP<input autoFocus required inputMode="decimal" value={draft.amount} onChange={e=>setDraft({...draft,amount:e.target.value})} placeholder="250.00"/></label><label className="field-label">Financial account<select required value={draft.accountId} onChange={e=>setDraft({...draft,accountId:e.target.value})}><option value="">Choose account</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.name}{a.isDefault?" · default":""}</option>)}</select></label><label className="field-label span-2">Description (optional)<input maxLength={180} value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})} placeholder="Add a note"/></label><label className="field-label span-2">Category<select required value={draft.categoryId} onChange={e=>setDraft({...draft,categoryId:e.target.value})}><option value="">Choose category</option>{categories.map(category=><option key={category.id} value={category.id}>{category.name} · {category.type}</option>)}</select></label><label className="field-label span-2">Date<input type="date" required value={draft.date} onChange={e=>setDraft({...draft,date:e.target.value})}/></label></div>{error&&<p className="error-text" role="alert" style={{marginTop:12}}>{error}</p>}<div className="modal-footer"><button type="button" className="button" onClick={()=>setOpen(false)}>Cancel</button><button disabled={busy} className="button button-primary">{busy?"Saving…":editing?"Save changes":"Save transaction"}</button></div></form></section></div>}
  </div>;
}
